# This file is part of the Data Cleaning Library (openclean).
#
# Copyright (C) 2018-2020 New York University.
#
# openclean is released under the Revised BSD License. See file LICENSE for
# full license details.

"""Factory for scalar feature functins."""

from abc import ABCMeta, abstractmethod


class FeatureFunctionFactory(metaclass=ABCMeta):
    """Feature functin factory allows to create feature functions that require
    to pre-compute statistics (e.g., min or max values) for a data stream
    before generating numeric feature for values in the stream.
    """
    @abstractmethod
    def get_function(self, data):
        """Create an instance of the feature function that is generated by the
        factory. The returned function will be called for each of the values
        in the given values during feature vector generation.

        Parameters
        ----------
        data: list
            List of value sin the stream.

        Returns
        -------
        callable
        """
        raise NotImplementedError()
